[package]
name = "luau0-src"
version = "0.5.2+luau561"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]
edition = "2021"
repository = "https://github.com/khvzak/luau-src-rs"
keywords = ["lua", "luau", "roblox"]
readme = "README.md"
license = "MIT"
description = """
Minimal sources of Roblox Luau and logic to build them.
"""

[workspace]
members = ["testcrate"]

[dependencies]
cc = "1.0.72"
